/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package bomboman;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.DatagramPacket;
import java.net.InetAddress;
import java.net.MulticastSocket;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author fcomputer
 */
public abstract class Client extends javax.swing.JFrame {

    private Boolean client_online = true;
    private DefaultListModel listOrang = new DefaultListModel();
    private DefaultListModel listServer = new DefaultListModel();
    private Thread ListRoom;
    private ArrayList<String> daftarOrang = new ArrayList<>();

    /**
     * Creates new form Client
     */
    public Client() {
        initComponents();
        client_online = true;
        addWindowListener(new Client.WindowEventHandler());
        Client.this.setLocationRelativeTo(null);
        lstOrang.setModel(listOrang);
        lstServer.setModel(listServer);
        String nama = JOptionPane.showInputDialog("Please enter your name : ");
        if (nama != null && nama.length() > 0) {
            lblNama.setText(nama);
            CreateConnection(nama);
        } else {
            JOptionPane.showMessageDialog(null, "Invalid client name!", "Error", 0);
            dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        }
    }

    class WindowEventHandler extends WindowAdapter {
        @Override
        public void windowClosing(WindowEvent evt) {
            client_online = false;
            backToMenu();
        }
    }

    public void CreateConnection(final String namaUser) {

        ListRoom = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    System.out.println("Client running...");
                    InetAddress multicastAddress = InetAddress.getByName("224.0.0.2");
                    lblIPAddress.setText(InetAddress.getLocalHost().getHostAddress());
                    int multicastPort = 9693;

                    MulticastSocket ms = new MulticastSocket(multicastPort);
                    ms.joinGroup(multicastAddress);

                    String ip;
                    String message;

                    while (client_online) {
                        byte[] buffer = new byte[8192];
                        DatagramPacket dp = new DatagramPacket(buffer, buffer.length);
                        ms.receive(dp);
                        message = new String(buffer, 0, buffer.length);
                        System.out.println("Received Message : " + message.trim());
                        String cut[] = message.trim().split("-");

                        if (cut.length > 3) {
                            if (!daftarOrang.contains(cut[0] + "-" + cut[3])) {
                                daftarOrang.add(cut[0] + "-" + cut[3]);
                            }
                        }
                        ip = (cut[0]);
                        if (ip.contains("%%")) {
                            listServer.clear();
                            daftarOrang.clear();
                        } else if (ip.contains(".")) {
                            String ls = cut[1] + " (" + cut[0] + ")";
                            if (!listServer.contains(ls)) {
                                listServer.addElement(ls);
                            }
                        }

                    }
                    System.out.println("Client Killed");
                } catch (UnknownHostException ex) {
                    Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
        ListRoom.start();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstServer = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstOrang = new javax.swing.JList();
        cmdJoin = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblIPAddress = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        cmdBack = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Join Room");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lstServer.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lstServer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstServerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lstServer);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 140, 380));

        lstOrang.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jScrollPane2.setViewportView(lstOrang);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 330, 380));

        cmdJoin.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        cmdJoin.setText("Join");
        cmdJoin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdJoinActionPerformed(evt);
            }
        });
        getContentPane().add(cmdJoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 120, 60));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Your IP Address :");

        lblIPAddress.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblIPAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblIPAddress.setText("192.168.1.1");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Your Name :");
        jLabel5.setToolTipText("");

        lblNama.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblNama.setForeground(new java.awt.Color(255, 255, 255));
        lblNama.setText("Anonymous");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIPAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIPAddress)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblNama))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 350, 60));

        cmdBack.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        cmdBack.setForeground(new java.awt.Color(255, 255, 255));
        cmdBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomboman/gambar/back.png"))); // NOI18N
        cmdBack.setText(" Back");
        cmdBack.setToolTipText("");
        cmdBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmdBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdBackMouseClicked(evt);
            }
        });
        getContentPane().add(cmdBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 130, 80));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Join Room");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 190, 60));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("Join Room");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 190, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bomboman/gambar/back.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdJoinActionPerformed
        try {
            if (lstServer.getSelectedValue() != null) {
                System.out.println(listOrang.size());
                if (listOrang.size() < 4) {
                    System.out.println(lstServer.getSelectedValue());

                    String ip = (String) lstServer.getSelectedValue();
                    String getIP = ip.substring(ip.indexOf("(") + 1, ip.indexOf(")")).trim();

                    // Registrasikan nama kamu
                    Socket client = new Socket(getIP, 9693);
                    PrintWriter out = new PrintWriter(client.getOutputStream());
                    out.println(lblNama.getText().toString());
                    out.flush();
                    listOrang.clear();
                    listServer.clear();
                    this.setVisible(false);
                    BomboMain bomb = new BomboMain(false, getIP, lblNama.getText().toString()) {
                        @Override
                        public void sudahSelesai() {
                            Client.this.setVisible(true);
                        }
                    };
                    bomb.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(null, "Sorry, room is full!");
                }
            }
        } catch (UnknownHostException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Client.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cmdJoinActionPerformed

    public abstract void backToMenu();

    private void cmdBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdBackMouseClicked
        ListRoom.interrupt();
        dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        backToMenu();
    }//GEN-LAST:event_cmdBackMouseClicked

    private void lstServerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstServerMouseClicked
        listOrang.removeAllElements();
        for (int i = 0; i < daftarOrang.size(); i++) {
            String ip = (String) lstServer.getSelectedValue();
            // cek apakah string tidak kosong
            if (ip != null && ip.length() > 2) {
                String getIP = ip.substring(ip.indexOf("(") + 1, ip.indexOf(")")).trim();
                if (daftarOrang.get(i).contains(getIP)) {
                    String potong[] = daftarOrang.get(i).split("-");
                    String pisah[] = potong[1].split(":");
                    for (int j = 0; j < pisah.length; j++) {
                        listOrang.addElement(pisah[j]);
                    }
                }
            }
        }



    }//GEN-LAST:event_lstServerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("SystemLookAndFeel".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cmdBack;
    private javax.swing.JButton cmdJoin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblIPAddress;
    private javax.swing.JLabel lblNama;
    private javax.swing.JList lstOrang;
    private javax.swing.JList lstServer;
    // End of variables declaration//GEN-END:variables
}
